### ISSUE TITLE
Bearings View not working

### ISSUE THREAD

**Issue by FootPrintStudio** [jeetsukumaran/obsidian-bearings#2]
First I'd like to say that I love the plugin, it's the perfect mix of Metafolders and Breadcrumbs for me, and has replaced both on all my Vaults; however, I don't seem to be able to get the bearings view code blocks to work. I might be using it wrong, in which case more documentation is needed, or it might be broken.

From what I can tell from the readme, all that's needed is to simply add the code block as it is shown. Is more content required for a query or is meant to be empty?

Also, are there future plans to make the role labels visible within some form of display (code block view, navigation bar)? That would definitely cement this plugin as my go-to for vault organization. I'm thinking of Breadcrumbs' matrix view or page view.

**Comment by jeetsukumaran** [comment]
Thanks for your kind comments! It's always good to hear about something being useful to others :)

(1) With respect to the codeblock, yes, in principle just having: 

~~~
```bearings
````
~~~

on a page should bring up all relationships to/from *that* particular page.( Later on, I plan to add a YAML parser that allows specification of a differnt focal file, filters etc.)

When you say it doesn't work, what exactly is the issue? E.g., blank, or not showing the correct relationships, etc?  I know there are some glitches that need to be sorted out in code blocks (e.g. in not auto-refreshing when pages update, and they might need to be manually refreshed), but there are also numerous external issues (e.g., dataview not installed, metadata block with syntax errors so Obsidian cannot understand it, different relationship names or typos in the field names etc.).

Below are some test cases that you could add to your vault to see if it works:

This is how things should like when "running on empty", i.e. everything working but no data:

~~~
```bearings
```
~~~

![image](https://github.com/jeetsukumaran/obsidian-bearings/assets/26183/d3499e86-34a9-43c5-bd87-21ab6bd4dd97)

This the simplest graph, a single self-linked note:

~~~
---
entry-parents:
  - "[[Untitled 1]]"
title: "**Hello** from *Note 1*"
---

```bearings
```
~~~


![image](https://github.com/jeetsukumaran/obsidian-bearings/assets/26183/8acc39fc-b762-41ee-a2bc-98dcc4f3abcc)

which can be extended:

![image](https://github.com/jeetsukumaran/obsidian-bearings/assets/26183/a5407398-e558-42c9-b3d6-260495f8a139)

(2) With respect to future plans -- a previous incarnation of this plugin (a javascript prototype) indeed did have some sort of indicator for the relationships. After a lot of experimentation, I settled on the most compact way would be for the arrows to be customizable relationship-specific unicode/character/strings, so, e.g., A `parent-child` relationship could be indicated by `⋋`  connecting the node to the edge while a `classifier-classified` relationship could be `∋` (for e.g.). Plus some sort a tool-tip /overlay description. There are also plans to support tags like the glyphs..

**Comment by FootPrintStudio** [comment]
Thanks for the help.

This works as intended.
````
```bearings
```
````

However, in the readme, this is the code block shown, might want to change that.
````
```bearings-view
```
````

**Comment by jeetsukumaran** [comment]
Ah, got it. Yep, that's a documentation issue. Fixed now, thanks!

**Comment by jeetsukumaran** [comment]
Just a quick note -- as it happens some indication of the relationships is going to make into the next release: 
![image](https://github.com/jeetsukumaran/obsidian-bearings/assets/26183/5ec8417d-4faf-4bf2-8756-c6f5729b5f1b)

along with lots of richer support for node creation.

**Comment by FootPrintStudio** [comment]
Thanks for the heads up, I'll keep an eye on it.
